In [1]:
import rlssm
import pandas as pd

/Users/Khamir/opt/anaconda3/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
import pandas as pd
import numpy as np

In [3]:
from rlssm.random import generate_task_design_fontanesi, simulate_rl_2alternatives, simulate_hier_rl_2alternatives
from rlssm.random import simulate_rlddm_2alternatives, simulate_hier_rlddm_2alternatives
from rlssm.random import simulate_rlrdm_2alternatives

### non hierarchical

In [4]:
dm = generate_task_design_fontanesi(n_trials_block=80,
                                    n_blocks=3,
                                    n_participants=1,
                                    trial_types=['1-2', '1-3', '2-4', '3-4'],
                                    mean_options=[34, 38, 50, 54],
                                    sd_options=[5, 5, 5, 5])

The task will be created with the following 4 options: [1 2 3 4].
With mean (respectively): [34, 38, 50, 54] and SD: [5, 5, 5, 5].

In [5]:
data = simulate_rlrdm_2alternatives(task_design=dm,
                                     gen_alpha=0.1,
                                     gen_drift_scaling=.1,
                                     gen_threshold=1,
                                     gen_ndt=.23,
                                     initial_value_learning=0)

INFO:numexpr.utils:NumExpr defaulting to 4 threads.

In [6]:
data

                                     trial trial_type  inc_option  cor_option  \
participant block_label trial_block
1           1           1                1        1-2           1           2
                        2                2        3-4           3           4
                        3                3        1-3           1           3
                        4                4        3-4           3           4
                        5                5        2-4           2           4
...                                    ...        ...         ...         ...
            3           76             236        1-2           1           2
                        77             237        2-4           2           4
                        78             238        1-3           1           3
                        79             239        1-2           1           2
                        80             240        1-2           1           2

                                     f_inc  f_cor  alpha      Q_cor  \
participant block_label trial_block
1           1           1               27     48    0.1   0.000000
                        2               40     61    0.1   6.100000
                        3               34     49    0.1   8.500000
                        4               59     57    0.1  11.190000
                        5               34     53    0.1  15.371000
...                                    ...    ...    ...        ...
            3           76              37     33    0.1  37.407123
                        77              37     52    0.1  52.576760
                        78              38     51    0.1  48.905837
                        79              42     35    0.1  37.129770
                        80              34     37    0.1  37.116793

                                         Q_inc  drift_scaling  threshold  \
participant block_label trial_block
1           1           1             0.000000            0.1          1
                        2             4.000000            0.1          1
                        3             3.400000            0.1          1
                        4            13.550000            0.1          1
                        5             3.400000            0.1          1
...                                        ...            ...        ...
            3           76           33.128076            0.1          1
                        77           37.366411            0.1          1
                        78           33.615268            0.1          1
                        79           34.453741            0.1          1
                        80           34.408367            0.1          1

                                      ndt  cor_drift  inc_drift     rt  \
participant block_label trial_block
1           1           1            0.23   0.000000   0.000000  2.910
                        2            0.23   0.610000   0.400000  0.392
                        3            0.23   0.850000   0.340000  2.354
                        4            0.23   1.119000   1.355000  0.761
                        5            0.23   1.537100   0.340000  0.514
...                                   ...        ...        ...    ...
            3           76           0.23   3.740712   3.312808  0.378
                        77           0.23   5.257676   3.736641  0.364
                        78           0.23   4.890584   3.361527  0.388
                        79           0.23   3.712977   3.445374  0.561
                        80           0.23   3.711679   3.440837  0.354

                                     accuracy
participant block_label trial_block
1           1           1                 0.0
                        2                 0.0
                        3                 0.0
                        4                 0.0
                        5                 1.0
...                                       ...
            3           76                1.0
                        77                1.0
                        78                0.0
                        79                1.0
                        80                1.0

[240 rows x 16 columns]

#### simple rl

In [5]:
dm

,participant,block_label,trial_block,trial,trial_type,inc_option,cor_option,f_inc,f_cor
0,1,1,1,1,1-2,1,2,41,37
1,1,1,2,2,2-4,2,4,46,47
2,1,1,3,3,1-3,1,3,33,44
3,1,1,4,4,3-4,3,4,45,55
4,1,1,5,5,3-4,3,4,48,58
...,...,...,...,...,...,...,...,...,...
235,1,3,76,236,1-3,1,3,31,48
236,1,3,77,237,3-4,3,4,47,50
237,1,3,78,238,1-2,1,2,38,36
238,1,3,79,239,1-2,1,2,32,41
239,1,3,80,240,3-4,3,4,52,50

In [5]:
data = simulate_rl_2alternatives(task_design=dm,
                                 gen_alpha=.1,
                                 gen_sensitivity=.5,
                                 initial_value_learning=20)

In [6]:
data

                                     trial trial_type  inc_option  cor_option  \
participant block_label trial_block
1           1           1                1        2-4           2           4
                        2                2        2-4           2           4
                        3                3        3-4           3           4
                        4                4        3-4           3           4
                        5                5        3-4           3           4
...                                    ...        ...         ...         ...
            3           76             236        1-3           1           3
                        77             237        1-2           1           2
                        78             238        1-3           1           3
                        79             239        3-4           3           4
                        80             240        2-4           2           4

                                     f_inc  f_cor  alpha      Q_cor  \
participant block_label trial_block
1           1           1               39     55    0.1  20.000000
                        2               43     61    0.1  24.100000
                        3               41     55    0.1  27.190000
                        4               50     59    0.1  30.371000
                        5               49     53    0.1  32.633900
...                                    ...    ...    ...        ...
            3           76              34     55    0.1  50.502486
                        77              32     43    0.1  38.814774
                        78              38     48    0.1  50.252238
                        79              51     57    0.1  53.958058
                        80              29     54    0.1  53.962252

                                         Q_inc  sensitivity     p_cor  \
participant block_label trial_block
1           1           1            20.000000          0.5  0.500000
                        2            22.300000          0.5  0.710950
                        3            22.100000          0.5  0.927237
                        4            24.890000          0.5  0.939375
                        5            27.301000          0.5  0.935018
...                                        ...          ...       ...
            3           76           34.118649          0.5  0.999723
                        77           33.906784          0.5  0.920853
                        78           34.316106          0.5  0.999654
                        79           50.327014          0.5  0.860028
                        80           37.833296          0.5  0.999686

                                     accuracy
participant block_label trial_block
1           1           1                   0
                        2                   0
                        3                   1
                        4                   0
                        5                   1
...                                       ...
            3           76                  1
                        77                  1
                        78                  1
                        79                  1
                        80                  1

[240 rows x 12 columns]

In [7]:
data = simulate_rl_2alternatives(task_design=dm,
                                 gen_alpha=[.2, .05],
                                 gen_sensitivity=.5,
                                 initial_value_learning=20)

In [8]:
data

                                     trial trial_type  inc_option  cor_option  \
participant block_label trial_block
1           1           1                1        2-4           2           4
                        2                2        2-4           2           4
                        3                3        3-4           3           4
                        4                4        3-4           3           4
                        5                5        3-4           3           4
...                                    ...        ...         ...         ...
            3           76             236        1-3           1           3
                        77             237        1-2           1           2
                        78             238        1-3           1           3
                        79             239        3-4           3           4
                        80             240        2-4           2           4

                                     f_inc  f_cor  alpha_pos  alpha_neg  \
participant block_label trial_block
1           1           1               39     55        0.2       0.05
                        2               43     61        0.2       0.05
                        3               41     55        0.2       0.05
                        4               50     59        0.2       0.05
                        5               49     53        0.2       0.05
...                                    ...    ...        ...        ...
            3           76              34     55        0.2       0.05
                        77              32     43        0.2       0.05
                        78              38     48        0.2       0.05
                        79              51     57        0.2       0.05
                        80              29     54        0.2       0.05

                                         Q_cor      Q_inc  sensitivity  \
participant block_label trial_block
1           1           1            20.000000  20.000000          0.5
                        2            28.200000  24.600000          0.5
                        3            33.560000  24.200000          0.5
                        4            38.648000  29.360000          0.5
                        5            41.518400  33.288000          0.5
...                                        ...        ...          ...
            3           76           53.868294  36.565005          0.5
                        77           41.310947  36.336754          0.5
                        78           53.574879  36.669403          0.5
                        79           56.728411  53.446135          0.5
                        80           56.591990  40.695400          0.5

                                        p_cor  accuracy
participant block_label trial_block
1           1           1            0.500000         1
                        2            0.858149         1
                        3            0.990806         1
                        4            0.990473         1
                        5            0.983939         1
...                                       ...       ...
            3           76           0.999825         1
                        77           0.923232         1
                        78           0.999787         1
                        79           0.837690         1
                        80           0.999647         1

[240 rows x 13 columns]

#### rlddm

In [9]:
data = simulate_rlddm_2alternatives(task_design=dm,
                                     gen_alpha=.1,
                                     gen_drift_scaling=.1,
                                     gen_threshold=1,
                                     gen_ndt=.23,
                                     initial_value_learning=0)

INFO:numexpr.utils:NumExpr defaulting to 8 threads.

In [10]:
data

                                     trial trial_type  inc_option  cor_option  \
participant block_label trial_block
1           1           1                1        2-4           2           4
                        2                2        2-4           2           4
                        3                3        3-4           3           4
                        4                4        3-4           3           4
                        5                5        3-4           3           4
...                                    ...        ...         ...         ...
            3           76             236        1-3           1           3
                        77             237        1-2           1           2
                        78             238        1-3           1           3
                        79             239        3-4           3           4
                        80             240        2-4           2           4

                                     f_inc  f_cor  alpha      Q_cor  \
participant block_label trial_block
1           1           1               39     55    0.1   0.000000
                        2               43     61    0.1   6.100000
                        3               41     55    0.1  10.990000
                        4               50     59    0.1  15.791000
                        5               49     53    0.1  19.511900
...                                    ...    ...    ...        ...
            3           76              34     55    0.1  50.137526
                        77              32     43    0.1  38.449814
                        78              38     48    0.1  49.923774
                        79              51     57    0.1  53.593098
                        80              29     54    0.1  53.633788

                                         Q_inc  drift_scaling  threshold  \
participant block_label trial_block
1           1           1             0.000000            0.1          1
                        2             4.300000            0.1          1
                        3             4.100000            0.1          1
                        4             8.690000            0.1          1
                        5            12.721000            0.1          1
...                                        ...            ...        ...
            3           76           33.753689            0.1          1
                        77           33.578320            0.1          1
                        78           34.020488            0.1          1
                        79           50.031396            0.1          1
                        80           37.504832            0.1          1

                                      ndt     drift     rt  accuracy
participant block_label trial_block
1           1           1            0.23  0.000000  0.658       1.0
                        2            0.23  0.180000  0.331       0.0
                        3            0.23  0.689000  0.454       1.0
                        4            0.23  0.710100  0.437       1.0
                        5            0.23  0.679090  0.454       1.0
...                                   ...       ...    ...       ...
            3           76           0.23  1.638384  0.310       1.0
                        77           0.23  0.487149  0.562       1.0
                        78           0.23  1.590329  0.547       0.0
                        79           0.23  0.356170  0.458       1.0
                        80           0.23  1.612896  0.291       1.0

[240 rows x 15 columns]

In [11]:
data = simulate_rlddm_2alternatives(task_design=dm,
                                     gen_alpha=[.1, .01],
                                     gen_drift_scaling=.1,
                                     gen_threshold=1,
                                     gen_ndt=.23,
                                     initial_value_learning=0)

In [12]:
data.head()

                                     trial trial_type  inc_option  cor_option  \
participant block_label trial_block
1           1           1                1        2-4           2           4
                        2                2        2-4           2           4
                        3                3        3-4           3           4
                        4                4        3-4           3           4
                        5                5        3-4           3           4

                                     f_inc  f_cor  alpha_pos  alpha_neg  \
participant block_label trial_block
1           1           1               39     55        0.1       0.01
                        2               43     61        0.1       0.01
                        3               41     55        0.1       0.01
                        4               50     59        0.1       0.01
                        5               49     53        0.1       0.01

                                       Q_cor   Q_inc  drift_scaling  \
participant block_label trial_block
1           1           1             0.0000   0.000            0.1
                        2             6.1000   4.300            0.1
                        3            10.9900   4.100            0.1
                        4            15.7910   8.690            0.1
                        5            19.5119  12.721            0.1

                                     threshold   ndt    drift     rt  accuracy
participant block_label trial_block
1           1           1                    1  0.23  0.00000  0.522       0.0
                        2                    1  0.23  0.18000  0.509       0.0
                        3                    1  0.23  0.68900  0.362       0.0
                        4                    1  0.23  0.71010  0.357       0.0
                        5                    1  0.23  0.67909  0.294       1.0

### hierarchical

In [13]:
dm = generate_task_design_fontanesi(n_trials_block=80,
                                    n_blocks=3,
                                    n_participants=30,
                                    trial_types=['1-2', '1-3', '2-4', '3-4'],
                                    mean_options=[34, 38, 50, 54],
                                    sd_options=[5, 5, 5, 5])

The task will be created with the following 4 options: [1 2 3 4].
With mean (respectively): [34, 38, 50, 54] and SD: [5, 5, 5, 5].

#### simple rl

In [14]:
data = simulate_hier_rl_2alternatives(task_design=dm,
                                      gen_mu_alpha=-.5,
                                      gen_sd_alpha=.1,
                                      gen_mu_sensitivity=.5,
                                      gen_sd_sensitivity=.1,
                                      initial_value_learning=20)

In [15]:
data.head()

                                     trial trial_type  inc_option  cor_option  \
participant block_label trial_block
1           1           1                1        1-3           1           3
                        2                2        1-3           1           3
                        3                3        2-4           2           4
                        4                4        1-3           1           3
                        5                5        1-2           1           2

                                     f_inc  f_cor     alpha  sensitivity  \
participant block_label trial_block
1           1           1               41     46  0.351655     0.912314
                        2               43     57  0.351655     0.912314
                        3               43     60  0.351655     0.912314
                        4               35     52  0.351655     0.912314
                        5               40     33  0.351655     0.912314

                                         Q_cor      Q_inc     p_cor  accuracy
participant block_label trial_block
1           1           1            20.000000  20.000000  0.500000         1
                        2            33.011226  28.088060  0.988920         1
                        3            34.066191  28.088060  0.995739         1
                        4            39.688719  30.518676  0.999767         1
                        5            29.815367  33.852829  0.024520         0

In [16]:
data = simulate_hier_rl_2alternatives(task_design=dm,
                                      gen_mu_alpha=[-.5, -1],
                                      gen_sd_alpha=[.1, .1],
                                      gen_mu_sensitivity=.5,
                                      gen_sd_sensitivity=.1,
                                      initial_value_learning=20)

In [17]:
data

                                     trial trial_type  inc_option  cor_option  \
participant block_label trial_block
1           1           1                1        1-3           1           3
                        2                2        1-3           1           3
                        3                3        2-4           2           4
                        4                4        1-3           1           3
                        5                5        1-2           1           2
...                                    ...        ...         ...         ...
30          3           76             236        3-4           3           4
                        77             237        1-3           1           3
                        78             238        1-2           1           2
                        79             239        2-4           2           4
                        80             240        2-4           2           4

                                     f_inc  f_cor  alpha_pos  alpha_neg  \
participant block_label trial_block
1           1           1               41     46   0.304766   0.167025
                        2               43     57   0.304766   0.167025
                        3               43     60   0.304766   0.167025
                        4               35     52   0.304766   0.167025
                        5               40     33   0.304766   0.167025
...                                    ...    ...        ...        ...
30          3           76              33     54   0.373412   0.133162
                        77              36     43   0.373412   0.133162
                        78              39     35   0.373412   0.133162
                        79              41     46   0.373412   0.133162
                        80              42     49   0.373412   0.133162

                                     sensitivity      Q_cor      Q_inc  \
participant block_label trial_block
1           1           1               0.856509  20.000000  20.000000
                        2               0.856509  31.276348  27.009621
                        3               0.856509  32.190646  27.009621
                        4               0.856509  37.592215  29.444818
                        5               0.856509  28.835286  32.661680
...                                          ...        ...        ...
30          3           76              0.976304  57.887876  45.386813
                        77              0.976304  45.068979  36.249326
                        78              0.976304  37.607861  37.276461
                        79              0.976304  56.304859  38.874527
                        80              0.976304  55.332126  40.041617

                                        p_cor  accuracy
participant block_label trial_block
1           1           1            0.500000         1
                        2            0.974778         1
                        3            0.988314         1
                        4            0.999069         1
                        5            0.036357         0
...                                       ...       ...
30          3           76           0.999995         1
                        77           0.999818         1
                        78           0.580189         0
                        79           1.000000         1
                        80           1.000000         1

[7200 rows x 13 columns]

#### rlddm

In [18]:
data = simulate_hier_rlddm_2alternatives(task_design=dm,
                                          gen_mu_alpha=-.5,
                                          gen_sd_alpha=.1,
                                          gen_mu_drift_scaling=.1,
                                          gen_sd_drift_scaling=.5,
                                          gen_mu_threshold=1,
                                          gen_sd_threshold=.1,
                                          gen_mu_ndt=.23,
                                          gen_sd_ndt=.05,
                                          initial_value_learning=20)

In [19]:
data

                                     trial trial_type  inc_option  cor_option  \
participant block_label trial_block
1           1           1                1        1-3           1           3
                        2                2        1-3           1           3
                        3                3        2-4           2           4
                        4                4        1-3           1           3
                        5                5        1-2           1           2
...                                    ...        ...         ...         ...
30          3           76             236        3-4           3           4
                        77             237        1-3           1           3
                        78             238        1-2           1           2
                        79             239        2-4           2           4
                        80             240        2-4           2           4

                                     f_inc  f_cor     alpha  drift_scaling  \
participant block_label trial_block
1           1           1               41     46  0.264085       1.124549
                        2               43     57  0.264085       1.124549
                        3               43     60  0.264085       1.124549
                        4               35     52  0.264085       1.124549
                        5               40     33  0.264085       1.124549
...                                    ...    ...       ...            ...
30          3           76              33     54  0.311824       0.880337
                        77              36     43  0.311824       0.880337
                        78              39     35  0.311824       0.880337
                        79              41     46  0.311824       0.880337
                        80              42     49  0.311824       0.880337

                                     threshold       ndt      Q_cor  \
participant block_label trial_block
1           1           1             1.304761  0.822894  20.000000
                        2             1.304761  0.822894  29.771146
                        3             1.304761  0.822894  30.563402
                        4             1.304761  0.822894  35.641454
                        5             1.304761  0.822894  27.903021
...                                        ...       ...        ...
30          3           76            1.519930  0.850121  56.383404
                        77            1.519930  0.850121  41.528573
                        78            1.519930  0.850121  35.366026
                        79            1.519930  0.850121  53.145605
                        80            1.519930  0.850121  51.852904

                                         Q_inc      drift        rt  accuracy
participant block_label trial_block
1           1           1            20.000000   0.000000  0.919894       1.0
                        2            26.073956   4.157673  0.884894       1.0
                        3            26.073956   5.048602  0.921894       1.0
                        4            28.431191   8.108296  0.918894       1.0
                        5            31.486340  -4.029619  0.933894       0.0
...                                        ...        ...       ...       ...
30          3           76           40.861843  13.664201  0.944121       1.0
                        77           33.691705   6.899083  0.962121       1.0
                        78           35.346961   0.016783  1.429121       1.0
                        79           37.122837  14.105433  0.913121       1.0
                        80           38.643655  11.628588  0.912121       1.0

[7200 rows x 15 columns]

In [20]:
data = simulate_hier_rlddm_2alternatives(task_design=dm,
                                          gen_mu_alpha=[-.5, -1],
                                          gen_sd_alpha=[.1, .1],
                                          gen_mu_drift_scaling=.1,
                                          gen_sd_drift_scaling=.5,
                                          gen_mu_threshold=1,
                                          gen_sd_threshold=.1,
                                          gen_mu_ndt=.23,
                                          gen_sd_ndt=.05,
                                          initial_value_learning=20)

In [21]:
data

                                     trial trial_type  inc_option  cor_option  \
participant block_label trial_block
1           1           1                1        1-3           1           3
                        2                2        1-3           1           3
                        3                3        2-4           2           4
                        4                4        1-3           1           3
                        5                5        1-2           1           2
...                                    ...        ...         ...         ...
30          3           76             236        3-4           3           4
                        77             237        1-3           1           3
                        78             238        1-2           1           2
                        79             239        2-4           2           4
                        80             240        2-4           2           4

                                     f_inc  f_cor  alpha_pos  alpha_neg  \
participant block_label trial_block
1           1           1               41     46   0.371686   0.190000
                        2               43     57   0.371686   0.190000
                        3               43     60   0.371686   0.190000
                        4               35     52   0.371686   0.190000
                        5               40     33   0.371686   0.190000
...                                    ...    ...        ...        ...
30          3           76              33     54   0.343268   0.113315
                        77              36     43   0.343268   0.113315
                        78              39     35   0.343268   0.113315
                        79              41     46   0.343268   0.113315
                        80              42     49   0.343268   0.113315

                                     drift_scaling  threshold       ndt  \
participant block_label trial_block
1           1           1                 0.971811   1.316583  0.826529
                        2                 0.971811   1.316583  0.826529
                        3                 0.971811   1.316583  0.826529
                        4                 0.971811   1.316583  0.826529
                        5                 0.971811   1.316583  0.826529
...                                            ...        ...       ...
30          3           76                0.470670   1.349890  0.735485
                        77                0.470670   1.349890  0.735485
                        78                0.470670   1.349890  0.735485
                        79                0.470670   1.349890  0.735485
                        80                0.470670   1.349890  0.735485

                                         Q_cor      Q_inc     drift        rt  \
participant block_label trial_block
1           1           1            20.000000  20.000000  0.000000  1.224529
                        2            33.752380  28.548777  5.056920  0.926529
                        3            34.867438  28.548777  6.140545  0.910529
                        4            40.534764  30.946606  9.317879  0.873529
                        5            30.203234  34.311625 -3.992580  1.046529
...                                        ...        ...       ...       ...
30          3           76           57.856277  46.002268  5.579332  0.808485
                        77           45.662067  36.416700  4.351521  0.797485
                        78           37.784241  37.303463  0.226288  0.824485
                        79           56.512784  38.888107  8.295415  0.870485
                        80           55.661474  39.956319  7.391953  0.780485

                                     accuracy
participant block_label trial_block
1           1           1                 1.0
                        2                 1.0
                        3                 1.0
                        4                 1.0
                        5                 0.0
...                                       ...
30          3           76                1.0
                        77                1.0
                        78                1.0
                        79                1.0
                        80                1.0

[7200 rows x 16 columns]

In [22]:
pd.unique(data.alpha_pos)

array([0.37168594, 0.31060847, 0.37698265, 0.2660053 , 0.35572814,
       0.31342541, 0.31491082, 0.3430648 , 0.32041817, 0.35989942,
       0.28859259, 0.23653333, 0.27112004, 0.32725697, 0.22636016,
       0.37639867, 0.37391664, 0.28749828, 0.35693181, 0.31316383,
       0.31368379, 0.34497587, 0.30015316, 0.30205729, 0.29599375,
       0.37167677, 0.29882084, 0.30506306, 0.38042997, 0.34326758])

In [23]:
pd.unique(data.alpha_neg)

array([0.18999951, 0.16398421, 0.12735308, 0.16129338, 0.16691981,
       0.1710399 , 0.15301629, 0.17291803, 0.13739252, 0.15200283,
       0.13684924, 0.19215029, 0.14253043, 0.17005758, 0.19363897,
       0.12691004, 0.19460621, 0.17529005, 0.17247156, 0.17872124,
       0.16845923, 0.14215278, 0.13055232, 0.22646985, 0.15315005,
       0.23958478, 0.15094853, 0.16453297, 0.18302581, 0.11331486])

## simulate the DDM

In [24]:
from rlssm.random import simulate_ddm, simulate_hier_ddm

In [25]:
data = simulate_ddm(
    n_trials=300, 
    gen_drift=.6, 
    gen_drift_trialsd=.1,
    gen_threshold=1.4, 
    gen_ndt=.23)

In [26]:
data

                      drift  drift_trialmu  drift_trialsd  rel_sp  threshold  \
participant trial
1           1      0.510523            0.6            0.1     0.5        1.4
            2      0.468118            0.6            0.1     0.5        1.4
            3      0.644025            0.6            0.1     0.5        1.4
            4      0.485356            0.6            0.1     0.5        1.4
            5      0.425756            0.6            0.1     0.5        1.4
...                     ...            ...            ...     ...        ...
            296    0.648541            0.6            0.1     0.5        1.4
            297    0.638972            0.6            0.1     0.5        1.4
            298    0.713564            0.6            0.1     0.5        1.4
            299    0.562848            0.6            0.1     0.5        1.4
            300    0.639898            0.6            0.1     0.5        1.4

                    ndt     rt  accuracy
participant trial
1           1      0.23  0.651       1.0
            2      0.23  0.773       1.0
            3      0.23  0.483       1.0
            4      0.23  0.614       1.0
            5      0.23  0.434       1.0
...                 ...    ...       ...
            296    0.23  0.352       1.0
            297    0.23  0.893       1.0
            298    0.23  2.047       0.0
            299    0.23  0.511       1.0
            300    0.23  0.430       1.0

[300 rows x 8 columns]

In [27]:
data = simulate_hier_ddm(n_trials=100,
    n_participants=30,
    gen_mu_drift=1,
    gen_sd_drift=.5,
    gen_mu_threshold=1,
    gen_sd_threshold=.1,
    gen_mu_ndt=.23,
    gen_sd_ndt=.1)

In [28]:
data

                      drift  threshold       ndt        rt  accuracy
participant trial
1           1      1.228621   1.209129  0.759558  0.961558       1.0
            1      1.228621   1.209129  0.759558  0.880558       0.0
            1      1.228621   1.209129  0.759558  1.489558       1.0
            1      1.228621   1.209129  0.759558  0.976558       1.0
            1      1.228621   1.209129  0.759558  0.801558       0.0
...                     ...        ...       ...       ...       ...
30          100    1.211658   1.280704  0.864771  1.014771       1.0
            100    1.211658   1.280704  0.864771  1.104771       1.0
            100    1.211658   1.280704  0.864771  1.281771       1.0
            100    1.211658   1.280704  0.864771  1.007771       0.0
            100    1.211658   1.280704  0.864771  0.945771       1.0

[3000 rows x 5 columns]